import crypto from 'node:crypto';
import { and, asc, inArray, gte, gt, lt, notInArray, type SQL } from 'drizzle-orm';
import type { Database } from './index.js';
import { consumerNotifications } from './schema/index.js';

/**
 * A notification to append — the row fields minus the DB-managed id/createdAt.
 * `id` is generated by the repo (crypto.randomUUID(), matching PgJournal/bots);
 * `createdAt` defaults in the DB.
 */
export interface InsertConsumerNotification {
  type: string;
  ownerId: string;
  agentId?: string | null;
  botId?: string | null;
  payload: Record<string, unknown>;
}

/**
 * Cursor for `scanAfter` — the stable (createdAt, seenIds) pair, identical in
 * meaning to `PgJournal.scanAfter`. `seenIds` holds every notification id already
 * processed at the boundary timestamp, so the cursor is stable under timestamp
 * ties (rows inserted in one statement share a `created_at`).
 */
export interface ConsumerNotificationCursor {
  createdAt: Date;
  seenIds: string[];
}

export type ConsumerNotificationRow = typeof consumerNotifications.$inferSelect;

/**
 * Postgres-backed repository for the Traderton→consumer outbox
 * (`consumer_notifications`, Wave E / E3). Writes delivery records, serves them
 * cursor-wise to a polling relay, and prunes expired rows in batches.
 */
export class ConsumerNotificationRepository {
  constructor(private readonly db: Database) {}

  /** Append one notification. Generates the id; lets createdAt default in the DB. */
  async append(entry: InsertConsumerNotification): Promise<void> {
    await this.db.insert(consumerNotifications).values({
      id: crypto.randomUUID(),
      type: entry.type,
      ownerId: entry.ownerId,
      agentId: entry.agentId ?? null,
      botId: entry.botId ?? null,
      payload: entry.payload,
    });
  }

  /**
   * Cursor-based scan with a stable (createdAt, id) cursor pair — same ordering
   * and cursor semantics as `PgJournal.scanAfter`. Returns rows after the cursor,
   * ordered ascending (oldest first); the caller advances the cursor to the last
   * returned row's (createdAt, id). `types` filters by exact type (notification
   * types are exact strings, unlike the journal's prefix match).
   */
  async scanAfter(opts: {
    cursor?: ConsumerNotificationCursor;
    types?: string[];
    limit: number;
  }): Promise<ConsumerNotificationRow[]> {
    const conditions: SQL[] = [];

    if (opts.cursor) {
      if (opts.cursor.seenIds.length > 0) {
        // Include rows at or after the cursor timestamp, excluding already-seen
        // IDs. >= (not >) ensures new rows at the same timestamp are returned.
        conditions.push(gte(consumerNotifications.createdAt, opts.cursor.createdAt));
        conditions.push(notInArray(consumerNotifications.id, opts.cursor.seenIds));
      } else {
        // seenIds empty (defensive fallback): advance strictly past the timestamp.
        conditions.push(gt(consumerNotifications.createdAt, opts.cursor.createdAt));
      }
    }

    if (opts.types && opts.types.length > 0) {
      conditions.push(inArray(consumerNotifications.type, opts.types));
    }

    return this.db
      .select()
      .from(consumerNotifications)
      .where(conditions.length > 0 ? and(...conditions) : undefined)
      .orderBy(asc(consumerNotifications.createdAt), asc(consumerNotifications.id))
      .limit(opts.limit);
  }

  /**
   * Delete rows with `createdAt < cutoff` in batches of `batchSize`, looping
   * until none remain. Returns the total number deleted.
   *
   * Postgres can't LIMIT a plain DELETE, so each batch deletes the rows whose id
   * is in a bounded subselect. Every batch deletes at least one row (while rows
   * older than the cutoff exist) and the loop stops once a batch deletes fewer
   * than `batchSize`, so it always makes progress and terminates.
   */
  async deleteOlderThan(cutoff: Date, batchSize: number): Promise<number> {
    let total = 0;
    for (;;) {
      // Postgres can't LIMIT a plain DELETE, so bound each batch via a subselect
      // of ids. .returning() reports how many this batch removed.
      const batchIds = this.db
        .select({ id: consumerNotifications.id })
        .from(consumerNotifications)
        .where(lt(consumerNotifications.createdAt, cutoff))
        .limit(batchSize);

      const deleted = await this.db
        .delete(consumerNotifications)
        .where(inArray(consumerNotifications.id, batchIds))
        .returning({ id: consumerNotifications.id });

      total += deleted.length;
      if (deleted.length < batchSize) break;
    }
    return total;
  }
}
