import type { AgentWakePayload, HybridPricingIdentity, TechnicalConfig } from '@traderton/domain';
import type { ScoredSignal } from '@traderton/strategy';
import type { TechnicalPhaseResult } from './technical-phase.js';
import type { ScannerHealthResult, TechnicalScanState } from './scan-types.js';

// ─── Persisted Candidate Types ───────────────────────────────────────────────

/** Shape passed to onPersistScanMetrics for each scan. */
export interface ScanMetricInput {
  agentId: string;
  presetKey: string;
  presetBehaviorVersion: string;
  venueFamily: string;
  styleTier: 'economy' | 'standard' | 'premium';
  /** Scan-scope context: { discovered, symbolsSelected, eligible, fetched, scored, signals } */
  scanScope: Record<string, unknown>;
  scannedAt: string;
  candidatesDiscovered: number;
  candidatesScored: number;
  signalsGenerated: number;
  scanHealth: string;
  topConfidence: number | null;
  regimeBucket: string | null;
}

/** Shape passed to onPersistScanCandidates for each scored candidate. */
export interface PersistableScanCandidate {
  /** Unique ID for this candidate row (generated by the caller). */
  id: string;
  agentId: string;
  scannedAt: string;
  scanVersion: string;
  activePresetKey: string;
  presetBehaviorVersion: string;
  instrumentKind: 'orderbook' | 'perp' | 'swap' | 'dex'; // 'swap' reserved for future swap venue types
  venueFamily: string;
  styleTier: 'economy' | 'standard' | 'premium';
  symbol?: string;
  network?: string;
  address?: string;
  rawCandidateId?: string;
  resolutionStatus?: 'resolved' | 'unresolved' | 'ambiguous';
  candidateRank: number;
  scanScope?: string;
  signalFacts: Record<string, unknown>;
  confidence?: number;
  regimeBucket?: string;
  volatilityFact?: number;
  dataFreshnessTs?: string;
  disposition: 'discovered' | 'scored_no_signal' | 'entry_candidate' | 'exit_advisory' | 'rejected' | 'unresolved';
}

// ─── Fingerprint helpers ─────────────────────────────────────────────────────

/**
 * Bucket a confidence value into operator-configured bands so small noise
 * (e.g. 0.40 → 0.42) does not trigger a wake.
 */
export function bucketConfidence(value: number, size: number): string {
  return (Math.round(value / size) * size).toFixed(2);
}

/**
 * Build a deterministic fingerprint from the current scanner signal set.
 *
 * Top N signals are canonicalized alphabetically by instrumentId (not rank),
 * confidence is bucketed, and exit advisories are sorted. The resulting string
 * is stable across scans with the same set of signals, regardless of internal
 * ranking churn.
 */
export function computeSignalFingerprint(
  signals: ScoredSignal[],
  exitAdvisorySymbols: string[],
  regimePass: boolean | null,
  topN: number,
  bucketSize: number,
): string {
  const signalParts = signals
    .slice(0, topN)
    .map((signal) => `${signal.instrumentId}:${bucketConfidence(signal.confidence, bucketSize)}`)
    .sort();
  const exitPart =
    exitAdvisorySymbols.length > 0
      ? `exit:${[...exitAdvisorySymbols].sort().join(',')}`
      : 'exit:none';
  const regimePart =
    regimePass === null ? 'regime:unavailable' : regimePass ? 'regime:pass' : 'regime:block';
  return [...signalParts, exitPart, regimePart].join('|');
}

// ─── Public interface ────────────────────────────────────────────────────────

export interface CompleteTechnicalScanParams {
  phaseResult: TechnicalPhaseResult;
  technicalConfig: TechnicalConfig;
  agentId: string;
  isHybridMode: boolean;
  onTechnicalScanComplete?: (agentId: string, scan: TechnicalScanState) => void | Promise<void>;
  emitAgentWake?: (agentId: string, payload: AgentWakePayload) => Promise<void>;
  onJournalEvent?: (event: { type: string; payload?: Record<string, unknown> }) => void;
  /** Persist scanner candidate observations for the deterministic review pre-check. */
  onPersistScanCandidates?: (candidates: PersistableScanCandidate[]) => Promise<void>;
  /** Persist a per-scan metrics row for scanner health and signal observability. */
  onPersistScanMetrics?: (metrics: ScanMetricInput) => Promise<void>;
}

// ─── Scanner health classification ───────────────────────────────────────────

/**
 * Derive an operator-facing scanner health status from scan outcomes.
 *
 * Classification order is deliberate — each branch short-circuits:
 * 1. Overlap skip (scheduler concurrency / single-flight guard)
 * 2. No candidates discovered (venue binding or filter issue)
 * 3. Data-path failure (no candles fetched or no eligible symbols)
 * 4. Healthy no-signal (data was available and scored, strategy produced nothing)
 * 5. Healthy with signals
 */
export function deriveScannerHealth(phaseResult: TechnicalPhaseResult): ScannerHealthResult {
  const { overlapSkipped, candidatesDiscovered, eligibleCount, fetchedCount, candidatesScored, signalsGenerated } =
    phaseResult;

  if (overlapSkipped) {
    return { status: 'overlap_skipped', reason: 'Scan skipped — previous scan still in progress' };
  }

  if (candidatesDiscovered === 0) {
    return { status: 'no_candidates', reason: 'No candidates discovered — check venue binding and filters' };
  }

  // Data-path failure: no candles fetched or no eligible symbols
  if (fetchedCount === 0 || eligibleCount === 0) {
    return {
      status: 'data_path_failure',
      reason: `fetched=${fetchedCount}, eligible=${eligibleCount} — candle data unavailable`,
    };
  }

  // Healthy no-signal: data was available but strategy didn't produce signals.
  // Covers both "candidates scored but no signal" (conservative strategy) and
  // "no candidates passed scoring" (e.g. regime blocked all entries, threshold
  // filters excluded everything).  Both are healthy outcomes — the data path
  // worked, the strategy just said no.
  if (fetchedCount > 0 && signalsGenerated === 0) {
    const reason =
      candidatesScored > 0
        ? 'Data available, candidates scored, no signals generated — conservative strategy'
        : 'Data available but no candidates passed scoring filters — check regime or threshold config';
    return { status: 'healthy_no_signal', reason };
  }

  // Healthy with signals
  return { status: 'healthy_signals', reason: `${signalsGenerated} signal(s) generated` };
}

/**
 * Build a TechnicalScanState from a TechnicalPhaseResult, publish the scan event,
 * and emit a scanner wake when signals or exit advisories are present.
 *
 * Extracted from AgentTradingActor.runTechnicalScan() to enable deterministic
 * integration testing without actor infrastructure (no Redis, no venue).
 */
export async function completeTechnicalScan(params: CompleteTechnicalScanParams): Promise<TechnicalScanState> {
  const { phaseResult, technicalConfig, agentId, isHybridMode, onTechnicalScanComplete, emitAgentWake, onJournalEvent } =
    params;

  // Phase 4: Validate swap signals before entering TechnicalScanState.
  // A swap (venueType: 'swap') signal must have exact pricingIdentity
  // (kind: 'dex', chain, address) AND swapExecutionIdentity. Incomplete
  // swap signals are dropped — they must not trigger scanner wakes.
  const scanSignals: ScoredSignal[] = [];
  for (const signal of phaseResult.signals) {
    if (signal.venueType === 'swap') {
      const pricing = signal.pricingIdentity;
      const swapExec = signal.swapExecutionIdentity;
      const isValid =
        pricing?.kind === 'dex' &&
        !!pricing.chain &&
        !!pricing.address &&
        !!swapExec;
      if (!isValid) {
        if (onJournalEvent) {
          onJournalEvent({
            type: 'scanner.incomplete_swap_identity',
            payload: {
              agentId,
              symbol: signal.symbol,
              instrumentId: signal.instrumentId,
              chain: pricing?.chain ?? null,
              address: pricing?.address ?? null,
              hasPricingIdentity: !!pricing,
              hasDexKind: pricing?.kind === 'dex',
              hasChain: !!pricing?.chain,
              hasAddress: !!pricing?.address,
              hasSwapExecutionIdentity: !!swapExec,
            },
          });
        }
        continue;
      }
    }
    scanSignals.push(signal);
  }

  // Build pricing-identity sidecar for hybrid USD-to-base conversion.
  // Each signal now carries its own venue-aware pricing identity determined
  // during discovery.  Signals lacking an explicit pricing identity (e.g.
  // orderbook go_long signals without venue context) are skipped — the
  // hybrid evaluator cannot safely reprice them.
  const pricingIdentities: Record<string, HybridPricingIdentity> = {};
  for (const signal of scanSignals) {
    if (signal.pricingIdentity) {
      pricingIdentities[signal.instrumentId] = signal.pricingIdentity;
    }
  }

  const scan: TechnicalScanState = {
    timestamp: new Date().toISOString(),
    scanIntervalMs: technicalConfig.scanIntervalMs,
    regimeResult: phaseResult.regimeResult,
    signals: scanSignals,
    positionIndicators: phaseResult.positionIndicators,
    summary: phaseResult.summary,
    symbolOutcomes: phaseResult.symbolOutcomes,
    discovered: phaseResult.candidatesDiscovered,
    symbolsSelected: phaseResult.symbolsSelected,
    eligible: phaseResult.eligibleCount,
    fetched: phaseResult.fetchedCount,
    unsupported: phaseResult.unsupportedCount,
    fetchFailures: phaseResult.fetchFailures,
    breakerSkips: phaseResult.breakerSkips,
    signalsGenerated: scanSignals.length,
    overlapSkipped: phaseResult.overlapSkipped,
    pricingIdentities,
  };

  // Derive operator-facing scanner health classification from scan outcomes.
  // Use post-filter counts (scanSignals.length) rather than pre-filter
  // phaseResult.signalsGenerated so that swap signals dropped for incomplete
  // identity do not inflate the health status.
  const health = deriveScannerHealth({ ...phaseResult, signalsGenerated: scanSignals.length });
  scan.scannerHealth = health;

  const eligibleCount = phaseResult.eligibleCount;
  const fetchedCount = phaseResult.fetchedCount;

  // Journal the scanner health status for every scan so operators can
  // distinguish conservative no-signal scans from broken data paths.
  if (onJournalEvent) {
    onJournalEvent({
      type: `scanner.${health.status}`,
      payload: {
        agentId,
        reason: health.reason,
        discovered: scan.discovered,
        symbolsSelected: scan.symbolsSelected,
        eligible: eligibleCount,
        fetched: fetchedCount,
        scored: phaseResult.candidatesScored,
        signalsGenerated: scanSignals.length,
        unsupported: scan.unsupported,
        fetchFailures: scan.fetchFailures,
        timestamp: scan.timestamp,
      },
    });
  }

  // Forward the completed scan before emitting a wake so the agent runtime
  // can ingest fresh scan state before it routes into the hybrid evaluator.
  // NOTE: errors from onTechnicalScanComplete are intentionally NOT swallowed —
  // if forwarding fails, the wake is skipped (the caller's catch block handles logging).
  if (onTechnicalScanComplete) {
    await onTechnicalScanComplete(agentId, scan);
  }

  // If agent has hybrid mode and scanner found signals or exit advisories, emit a wake.
  const hasExitAdvisories = phaseResult.positionIndicators.some((ind) => ind.exitAdvisory === true);
  const shouldWake = (scanSignals.length > 0 || hasExitAdvisories) && isHybridMode && !!emitAgentWake;

  if (shouldWake && emitAgentWake) {
    const topSignal = scanSignals[0];
    const exitAdvisorySymbols = phaseResult.positionIndicators
      .filter((ind) => ind.exitAdvisory === true)
      .map((ind) => ind.symbol);

    await emitAgentWake(agentId, {
      wakeId: crypto.randomUUID(),
      source: 'scanner',
      reason: [
        scanSignals.length > 0 ? `${scanSignals.length} signal(s)` : '',
        exitAdvisorySymbols.length > 0
          ? `${exitAdvisorySymbols.length} exit advisory/ies (${exitAdvisorySymbols.join(', ')})`
          : '',
      ]
        .filter(Boolean)
        .join(', ') || 'Scanner completed',
      priority: hasExitAdvisories ? 'high' : 'normal',
      eventIds: [],
      requestedAt: new Date().toISOString(),
      context: {
        scannerKind: 'signal_scoring' as const,
        signalCount: scanSignals.length,
        topSymbol: topSignal?.symbol,
        topConfidence: topSignal?.confidence,
        regimePass: phaseResult.regimeResult?.pass ?? null,
      },
    });
  }

  // ── Persist scanner candidate observations for deterministic review pre-check ──
  if (params.onPersistScanCandidates) {
    try {
      const scannedAt = new Date().toISOString();
      // Use scanSignals (post-validation) so invalid swap signals are not persisted.
      const filteredPhase = { ...phaseResult, signals: scanSignals };
      const candidates = buildPersistableCandidates(agentId, scannedAt, filteredPhase, technicalConfig);
      if (candidates.length > 0) {
        await params.onPersistScanCandidates(candidates);
      }
    } catch (err) {
      // Candidate persistence is best-effort — a failure must not crash the scan.
      // Logged by the actor.
    }
  }

  // ── Persist scan metrics for scanner health and signal observability ──
  if (params.onPersistScanMetrics) {
    const metrics = buildScanMetrics(agentId, phaseResult, health, technicalConfig, scanSignals.length);
    await params.onPersistScanMetrics(metrics);
  }

  return scan;
}

// ── Candidate persistence helpers ───────────────────────────────────────────

/**
 * Derive a style tier from the agent's technical config.
 * Falls back to 'standard' when not determinable.
 */
export function deriveStyleTier(technicalConfig: TechnicalConfig): 'economy' | 'standard' | 'premium' {
  const preset = (technicalConfig as Record<string, unknown>)['preset'];
  if (typeof preset === 'string') {
    if (preset.includes('economy')) return 'economy';
    if (preset.includes('premium')) return 'premium';
  }
  return 'standard';
}

/**
 * Derive a venue family from the agent's technical config.
 * Falls back to 'unknown' when not determinable.
 */
export function deriveVenueFamily(technicalConfig: TechnicalConfig): string {
  const venue = (technicalConfig as Record<string, unknown>)['venue'];
  if (typeof venue === 'string') return venue;
  return 'unknown';
}

/** @visibleForTesting */
/**
 * Build persistable candidates from the scan phase result.
 *
 * Entry-candidate signals and exit advisories are recorded. Candidates that
 * were discovered but did not produce signals are recorded as `scored_no_signal`
 * to enable peer-preset comparison in the review pre-check.
 */
export function buildPersistableCandidates(
  agentId: string,
  scannedAt: string,
  phaseResult: TechnicalPhaseResult,
  technicalConfig: TechnicalConfig,
): PersistableScanCandidate[] {
  const venueFamily = deriveVenueFamily(technicalConfig);
  const styleTier = deriveStyleTier(technicalConfig);
  const scanScope = `${venueFamily}_${styleTier}`;
  // Use a scan version derived from the configured indicators — this is an
  // approximate behavior version until Plan 012 delivers the authoritative one.
  const scanVersion = `ts-${styleTier}-v1`;
  const presetKey = (technicalConfig as Record<string, unknown>)['preset'] as string ?? 'unknown';
  const behaviorVersion = scanVersion;

  const candidates: PersistableScanCandidate[] = [];
  const seen = new Set<string>();

  // Entry signals
  for (let i = 0; i < phaseResult.signals.length; i++) {
    const signal = phaseResult.signals[i];
    if (!signal) continue;
    const id = crypto.randomUUID();
    const rawId = signal.instrumentId || signal.symbol;

    // Phase 4: DEX signals carry exact on-chain identity for execution and pricing.
    // Orderbook signals remain unchanged (instrumentKind: 'orderbook').
    const isSwap = signal.venueType === 'swap';
    const instrumentKind: PersistableScanCandidate['instrumentKind'] = isSwap ? 'dex' : 'orderbook';
    const network = isSwap ? signal.swapExecutionIdentity?.network : undefined;
    const address = isSwap ? signal.swapExecutionIdentity?.baseAddress : undefined;

    candidates.push({
      id,
      agentId,
      scannedAt,
      scanVersion,
      activePresetKey: presetKey,
      presetBehaviorVersion: behaviorVersion,
      instrumentKind,
      venueFamily,
      styleTier,
      symbol: signal.symbol,
      network,
      address,
      rawCandidateId: rawId,
      resolutionStatus: signal.symbol ? 'resolved' : 'unresolved',
      candidateRank: i + 1,
      scanScope,
      signalFacts: {
        signalType: 'entry_candidate',
        indication: signal.intent === 'go_long' ? 'bullish' : 'bearish',
        strength: signal.confidence,
        primaryIndicator: Object.entries(signal.indicators)
          .filter(([, v]) => v !== undefined)
          .map(([k]) => k)[0] ?? 'unknown',
        indicators: signal.indicators,
      },
      confidence: signal.confidence,
      regimeBucket: phaseResult.regimeResult?.pass ? 'favorable' : phaseResult.regimeResult?.pass === false ? 'blocked' : 'unavailable',
      volatilityFact: undefined,
      dataFreshnessTs: scannedAt,
      disposition: 'entry_candidate',
    });
    seen.add(rawId);
  }

  // Exit advisories from position indicators
  for (let i = 0; i < phaseResult.positionIndicators.length; i++) {
    const ind = phaseResult.positionIndicators[i];
    if (!ind || !ind.exitAdvisory) continue;
    const rawId = ind.instrumentId ?? ind.symbol;
    if (seen.has(rawId)) continue;

    const rank = candidates.length + 1;
    candidates.push({
      id: crypto.randomUUID(),
      agentId,
      scannedAt,
      scanVersion,
      activePresetKey: presetKey,
      presetBehaviorVersion: behaviorVersion,
      instrumentKind: 'orderbook',
      venueFamily,
      styleTier,
      symbol: ind.symbol,
      rawCandidateId: rawId,
      resolutionStatus: ind.symbol ? 'resolved' : 'unresolved',
      candidateRank: rank,
      scanScope,
      signalFacts: {
        signalType: 'exit_advisory',
        indication: ind.side === 'long' ? 'bearish' : 'bullish',
        rsi: ind.rsi,
      },
      confidence: undefined,
      regimeBucket: phaseResult.regimeResult?.pass ? 'favorable' : phaseResult.regimeResult?.pass === false ? 'blocked' : 'unavailable',
      volatilityFact: undefined,
      dataFreshnessTs: scannedAt,
      disposition: 'exit_advisory',
    });
    seen.add(rawId);
  }

  return candidates;
}

// ── Scan metrics persistence helper ────────────────────────────────────────

/**
 * Build a {@link ScanMetricInput} from the scan phase result and scanner health.
 * Mirrors the preset-metadata derivation in {@link buildPersistableCandidates}
 * so the scan metrics row carries the same preset identity as its candidate rows.
 */
function buildScanMetrics(
  agentId: string,
  phaseResult: TechnicalPhaseResult,
  health: ScannerHealthResult,
  technicalConfig: TechnicalConfig,
  /** Post-filter signal count (after swap identity validation). */
  postFilterSignalCount: number,
): ScanMetricInput {
  const venueFamily = deriveVenueFamily(technicalConfig);
  const styleTier = deriveStyleTier(technicalConfig);
  const presetKey = (technicalConfig as Record<string, unknown>)['preset'] as string ?? 'unknown';
  const presetBehaviorVersion = `ts-${styleTier}-v1`;

  const topConfidence =
    phaseResult.signals.length > 0
      ? Math.max(...phaseResult.signals.map((s) => s.confidence))
      : null;

  const regimeBucket =
    phaseResult.regimeResult?.pass === true ? 'favorable'
    : phaseResult.regimeResult?.pass === false ? 'blocked'
    : 'unavailable';

  return {
    agentId,
    presetKey,
    presetBehaviorVersion,
    venueFamily,
    styleTier,
    scanScope: {
      discovered: phaseResult.candidatesDiscovered,
      symbolsSelected: phaseResult.symbolsSelected,
      eligible: phaseResult.eligibleCount,
      fetched: phaseResult.fetchedCount,
      scored: phaseResult.candidatesScored,
      signals: postFilterSignalCount,
    },
    scannedAt: new Date().toISOString(),
    candidatesDiscovered: phaseResult.candidatesDiscovered,
    candidatesScored: phaseResult.candidatesScored,
    signalsGenerated: postFilterSignalCount,
    scanHealth: health.status,
    topConfidence,
    regimeBucket,
  };
}
