export { SimulatedClock } from './simulated-clock.js';
export { ArrayHistoricalDataFeed } from './historical-data-feed.js';
export type { HistoricalFrame, HistoricalDataFeed } from './historical-data-feed.js';
export { runBacktest } from './replay-runner.js';
export type { BacktestConfig } from './replay-runner.js';
export type { BacktestReport } from './backtest-report.js';
export { MarketDataRecorder } from './market-data-recorder.js';
export type { MarketEventRecord } from './market-data-recorder.js';
export { parseCsvToFrames } from './importers/index.js';
export type { CsvColumnMapping, CsvImportOptions } from './importers/index.js';
export { runValidation } from './validation-runner.js';
export type { ValidationComparison, ValidationResult, ValidationThresholds, DecisionDiff } from './validation-runner.js';
export { replayContexts, normalizeForReplay, normalizeForReplayBatch } from './context-replay.js';
export type { StoredDecisionContext, ContextReplayResult, ContextReplaySummary, PersistedDecisionContext, PersistedDecisionRow } from './context-replay.js';
